### ISSUE TITLE
Nuget release

### ISSUE THREAD

**Issue by ewinnington** [UiPath/CoreWF#1]
Will you be building a Nuget available somewhere so that people can directly include corewf in .net core apps?

Created a local nuget feed to consume it. 

And thank you for this!

**Comment by dmetzgar** [comment]
Use this for the runtime: https://www.nuget.org/packages/Microsoft.CoreWf/
And this for the ETW tracking participant: https://www.nuget.org/packages/Microsoft.CoreWf.EtwTracking/

Let me know if you run into any problems. I might have to change the package names (and namespaces) to not say Microsoft.

**Comment by ewinnington** [comment]
Thank you for the nuget. 

When using my local compiled version, I was able to run with little to no modifications our WF integrated code. Thats'a fantastic!

For the Nuget, I get an error message when I try to install it into my core-minimal test environment: 

Retrieving package 'Microsoft.CoreWf 1.0.0' from 'nuget.org'.
Installing NuGet package Microsoft.CoreWf.1.0.0.
Successfully installed 'Microsoft.CoreWf 1.0.0' to core-minimal
Executing nuget actions took 26.76 ms
========== Finished ==========
Time Elapsed: 00:00:00.3039885
PATH=.\node_modules.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "C:\Data-Dump\projects\core-minimal\src.vs\restore.dg"
log  : Restoring packages for C:\Data-Dump\projects\core-minimal\src\project.json...
error: Package Microsoft.CoreWf 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.CoreWf 1.0.0 supports: net (.NETFramework,Version=v0.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Writing lock file to disk. Path: C:\Data-Dump\projects\core-minimal\src\project.lock.json
log  : C:\Data-Dump\projects\core-minimal\src\core-minimal.xproj
log  : Restore failed in 1169ms.
Errors in C:\Data-Dump\projects\core-minimal\src\core-minimal.xproj
    Package Microsoft.CoreWf 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.CoreWf 1.0.0 supports: net (.NETFramework,Version=v0.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
