### ISSUE TITLE
Move Microsoft.CSharp.Activities to System.Activities project 

### ISSUE THREAD

**Issue by danielmeza** [UiPath/CoreWF#106]
In order to matain compatibility with the code generated by the designer we should move the Microsoft.CSharp.Activities to te System.Activities project.

This avoid us to change the generate xaml file from: 
` xmlns:mca="clr-namespace:Microsoft.CSharp.Activities;assembly=System.Ativities"`
 to: 
` xmlns:mca="clr-namespace:Microsoft.CSharp.Activities;assembly=UiPath.Workflow"`

**Comment by lbargaoanu** [comment]
The compilation will not be a part of System.Activities anymore. What I could do is to add a xaml namespace that doesn't depend on the assembly name. I guess that's what they should have done in the first place.

**Comment by lbargaoanu** [comment]
I think I found a workaround. I'll let you know here when you can try it.

**Comment by danielmeza** [comment]
Ok, as workaround I just change the assembly an evriting works as expected. I had a good experience proting a old project to .net core 3.1 this weekend I will create a wiki with that info to help other to migrate to.

**Comment by danielmeza** [comment]
@lbargaoanu as a note, the files I'm using here wasn't autogenerated with the UiPath.Workflow assembly, Those files was generated by the old xaml compile task, I have not try this with a clean compilation using this packages. In others works what I did was to copy the generated files on the obj and packing in the .net core project, cause the sdk style project had a issue when compiles workflows xaml ativities.

**Comment by lbargaoanu** [comment]
OK, so the latest is in. For backward compatibility, the clr namespace will work, but the idea is to use the xaml namespace, http://schemas.microsoft.com/netfx/2009/xaml/activities.
Thanks for reporting. I did realize it was a breaking change, but I was willing to do it :) I guess it's not really necessary.

**Comment by danielmeza** [comment]
Use http://schemas.microsoft.com/netfx/2009/xaml/activities. will be a nice solution. I will create e pull request with the project and items templates for visual studio. When you done with the alias letme know in order to update the items template. This way the new projects will have this by default and we can document this in the migration wiki guide.

**Comment by lbargaoanu** [comment]
I just did :)

**Comment by danielmeza** [comment]
I see the change [here](https://github.com/UiPath-Open/corewf/blob/3f66e6e681909b9f4b4c593b69e25ca03f25227e/src/UiPath.Workflow/AssemblyInfo.cs#L16-L17) but its pointing to System.Activities assembly and it should be pointing to UiPath.Worfllow
