### ISSUE TITLE
Rename namespace, assemblies, NuGet packages

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#11]
Remove Microsoft from the name since this is not an official Microsoft project.

**Comment by dmetzgar** [comment]
Renamed to CoreWf.

**Comment by ewinnington** [comment]
If the namespace of the Statements is different, how can we ensure compatibility with pre-existing XAML workflows? Will we have to do namespace remapping?

**Comment by dmetzgar** [comment]
The namespaces for the WF activities are typically using a URL like http://schemas.microsoft.com/netfx/2009/xaml/activities. We can map that to the CoreWf namespace. If there are any clr namespaces, we may have to use a xaml type resolver.

**Comment by ewinnington** [comment]
Ok, good. Cross that bridge when we get there.
