### ISSUE TITLE
Ambiguous reference System.Xaml 1.0 & System.Xaml 4.0

### ISSUE THREAD

**Issue by yekanchi** [UiPath/CoreWF#113]
when i try to serialize an activity i git this error:

```
StreamWriter sw = File.CreateText(@"C:\Workflows\add.xaml");
XamlWriter xw2 = ActivityXamlServices.CreateBuilderWriter(new XamlXmlWriter(sw, new XamlSchemaContext()));
XamlServices.Save(xw2, ab);
sw.Close();
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by lbargaoanu** [comment]
Also, what are you targeting?

**Comment by yekanchi** [comment]
> Also, what are you targeting?

The Problem Resolved!
I was Targeting .net core 3.1 and changed it it .net core 3.0
and now it works fine.

Thanks for quick help.
