### ISSUE TITLE
Can we use Orleans to build a workflow runtime

### ISSUE THREAD

**Issue by Cloud33** [UiPath/CoreWF#118]
Is that the case?

**Comment by lbargaoanu** [comment]
I have no idea :)

**Comment by dmetzgar** [comment]
Take a look at [Orleans.Activities](https://github.com/OrleansContrib/Orleans.Activities). It doesn't use CoreWF but shouldn't be too difficult to port.

**Comment by Cloud33** [comment]
Yes
