### ISSUE TITLE
Load XAML in .NET Core

### ISSUE THREAD

**Issue by csr17** [UiPath/CoreWF#120]
Hello,

I am trying load a XAML (as  the seem in the example) using CoreWF:

```
<Activity 
 x:Class="WorkflowConsoleApplication1.HelloWorld"
 xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities"
 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
  <Sequence>
    <WriteLine Text="Hello World!" />
  </Sequence>
</Activity>
```

```
   var result = CoreWf.XamlIntegration.ActivityXamlServices.Load(
                ActivityXamlServices.CreateBuilderReader(
                    new Portable.Xaml.XamlXmlReader(new MemoryStream(Encoding.UTF8.GetBytes(xamlDocument)))
                ));
```

But this return 'Root Element missing'. I think that this return this error due to the Activity Label belong to the library System.Activity and this library is not avalible in .NET Core.

Also in the Readme document I have see invoke the XAML this way:

`System.Activities.WorkflowInvoker.Invoke(helloWorldActivity);`

This haven't run in NET Core due the same reason the System.Activities is not avalible in NET Core.

So I don't understand why in the main page say that:

 'A port of the Windows Workflow Foundation (WF) runtime to .NET Core' 

But the example seem in this page not run in NET Core.

Regards.

**Comment by lbargaoanu** [comment]
Passing tests: https://github.com/UiPath-Open/corewf/tree/master/src/Test/TestCases.Workflows.
