### ISSUE TITLE
Error Install NuGet package 'UiPath.Workflow'

### ISSUE THREAD

**Issue by chamnan** [UiPath/CoreWF#127]
```
+PM> Install-Package UiPath.Workflow -Version 1.0.0-20201105-02 -Source https://www.myget.org/F/uipath-dev/api/v3/index.json
```
============================
```
Install-Package : Failed to retrieve information about 'UiPath.Workflow' from remote source 
'https://www.myget.org/F/uipath-dev/api/v2/symbolpackage/FindPackagesById()?id='UiPath.Workflow'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 404 (The symbols endpoint on your MyGet feed should not be configured as a NuGet package source.).
At line:1 char:1
+ Install-Package UiPath.Workflow -Version 1.0.0-20201105-02 -Source ht ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```
===========================
Error occurred while restoring NuGet packages: Failed to retrieve information about 'UiPath.Workflow' from remote source 'https://www.myget.org/F/uipath-dev/api/v2/symbolpackage/FindPackagesById()?id='UiPath.Workflow'&semVerLevel=2.0.0'.

**Comment by lbargaoanu** [comment]
It works for me. I'm guessing it's a problem on your end.

**Comment by chamnan** [comment]
> It works for me. I'm guessing it's a problem on your end.

To make it work, add NuGet Package Source URL: `https://www.myget.org/F/uipath-dev/`

Source URL in the instruction is not work [NuGet package](https://www.myget.org/feed/uipath-dev/package/nuget/UiPath.Workflow)
Browse the sources in this package using Visual Studio or WinDbg by configuring the following symbol server URL: 

~~`https://www.myget.org/F/uipath-dev/api/v2/symbolpackage/`~~
