### ISSUE TITLE
Split WriteLine activity into separate package

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#13]
Console writing is not included in all forms of the .NET standard. The WriteLine activity includes a default to write to the console. Separating it to its own package would allow us to support a lower .NET standard and be available to more platforms.

**Comment by ewinnington** [comment]
Console.Out is available from standard 1.3, if I believe [Apisof.net ](https://apisof.net/catalog/System.Console.Out). Is there that much of CoreWf that we can use at a lower than 1.3 standard to make it worth it to break out an essential statement? 
With 2.0 being necessary for DynamicActivity, where do you see it being used at a lower standard? 

And if we do the split, how can we layer .net standards CoreWf partial implementations on one another? What needs to change?

**Comment by dmetzgar** [comment]
If someone codes a workflow, as is used in the examples, they don't need DynamicActivity or XAML. If I'm building a workflow that runs on an IoT device, it may not have support for net standard 2.0. In some cases it may not be possible to split out and we could ifdef around it and produce different assemblies for different net standard versions.

**Comment by ewinnington** [comment]
Can we just ifdef the console.out to standard 1.3 and above? Below you have RequiredArgument on the TextWriter?

Update: Found a how to [multi target](https://www.bartwolff.com/Blog/2017/03/20/targeting-multiple-net-platforms-in-a-single-nuget-package-w)

**Comment by dmetzgar** [comment]
Sure. I'll need a smarter build and package process. I was just putting it off. 

BTW, multi-targeting is also covered in [my book](https://www.manning.com/books/dotnet-core-in-action).

**Comment by dmetzgar** [comment]
I looked into targeting .NET Standard 1.2 or lower. There are a lot of issues that come up, like with the WfEventSource class, the Channel property on EventAttribute is not supported and a lot of the ReflectionExtensions and TypeHelper methods are broken.  We'll just stick with 1.3 as the minimum for now. I'm currently trying to determine if automatic cachemetadata can be handled in 1.5 or 2.0.
