### ISSUE TITLE
Execute workflows with coreWF in AssemblyLoadContexts prevents unload

### ISSUE THREAD

**Issue by Colly2000** [UiPath/CoreWF#130]
To run workflows dynamical (load xaml- or code-activities at runtime in different versions), I want to start workflows in AssemblyLoadContexts. After executing, the unload function of AssemblyLoadContext is not able to clear the memory. I suspect, that some stong handles prevent deleting objects.

I don't know what to do to solve this problem. In my test environment, I only start an empty code-activity.
Can somebody help me.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
