### ISSUE TITLE
Add Transactions support

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#14]
System.Transactions is part of .NET Core 2.0. It only supports local transactions, but that should be enough for some workflow scenarios.

**Comment by ewinnington** [comment]
I started porting the transactions, but realized it was larger than I thought and needed some serious effort. Also, it will be much easier when we have Xaml support to generate transacted workflows. I'll get back to it when Xaml works on core and/or framework. 

Also, the tests will be vital here.
