### ISSUE TITLE
Port SQL Workflow Instance Store

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#15]
SWIS implements the InstanceStore abstract class and uses the client for SQL Server. It should be a straightforward port to .NET Standard.

**Comment by Diaskhan** [comment]
What plans ? Use ef core ? 
Or dapper for persistent? 

Using ef core could possible could be cross-rdbms !

**Comment by Diaskhan** [comment]
How large abstract api ?

**Comment by zehavibarak** [comment]
Has anyone implemented a store?

**Comment by zimmybln** [comment]
Is there any roadmap of this project? What are your plans for further steps? As far as I can see there is no option to create a workflow interactive. Is that right and if yes are there any plans to realize this?

**Comment by zehavibarak** [comment]
This project is a port of Microsoft WF code to Net Core. I’ve created a designer as part of a framework called BizDoc. If that’s what you’re interested in, maybe it can meet your needs.
[cid:image003.png@01D53AAF.DA354670]

________________________________

**Comment by smeddows** [comment]
Do you guys just copy from Reference Source and then clean it up/remove dead code and implement helper classes?

**Comment by acinep** [comment]
I've done this initial port and am getting into the testing now.  Who is the best person to touch base with before preparing a draft PR?
