### ISSUE TITLE
Contributing Guide has outdated Roadmap/Documentation Link

### ISSUE THREAD

**Issue by patrykgz** [UiPath/CoreWF#159]
The link found in "CONTRIBUTING.md" has a link to https://uipath-open.github.io/corewf which is not a valid website.

**Comment by lbargaoanu** [comment]
A PR is welcome. Just remove that line.

**Comment by patrykgz** [comment]
Is there a replacement public roadmap/documentation site, or is this internal now?

**Comment by lbargaoanu** [comment]
No.
