### ISSUE TITLE
Use Microsoft.Extensions.Localization instead of resxcodefilegenerator

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#16]
In the traditional build path in the .NET Framework, we have a tool called resxcodefilegenerator that turns a resx file into a cs file. Developers can then reference use properties to reference the various resource strings instead of calling ResourceManager directly. A new library introduced with .NET Core called Microsoft.Extensions.Localization includes the IStringLocalizer. The default language can be used as keys directly in the code since it will use the key if there is no resource string to be found for that culture. This also makes it easier to find where a particular error message comes from in the code.

**Comment by InariTheFox** [comment]
I wouldn't mind tackling this puppy and some other pieces around localization.

**Comment by dmetzgar** [comment]
@InariTheFox, that would be great. I have to port the current localized resx files over to restext. I'll try first with the en-us version and check it in.

**Comment by dmetzgar** [comment]
@InariTheFox, please take a look at #21 when you get a chance. This has the restext files for a bunch of languages. I'm kinda torn on whether the IStringLocalizer would be helpful. I'm not entirely satisfied with the SR class and how many lines it has just to do parameter substitution in the strings. It would be a lot of work to remove this SR class and I think it would depend on needing to add the IStringLocalizer to dependency injection and DI isn't initialized anywhere right now.

**Comment by InariTheFox** [comment]
Thanks. I'll take a stab at it this weekend!
