### ISSUE TITLE
Port remaining WF tests

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#19]
A lot of tests were left out because the features weren't implemented. Those tests can be ported and then disabled. As features are added, we can enable their tests.

**Comment by ewinnington** [comment]
This will be very helpful to check my progress and the validity of the modifications.

**Comment by dmetzgar** [comment]
There are no more tests for to port for the current capabilities of CoreWF. A lot of the other tests were on WF services, request/reply, etc., which use WCF underneath.
