### ISSUE TITLE
Tests using bookmarks don't serialize correctly

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#29]
Tests like [UnloadFlowchartWhileExecutingFlowConditionalCondition](https://github.com/dmetzgar/corewf/blob/678af1626bd825cfff5f0d6d0d72196fe62853df/test/TestCases.Activities/Flowchart/Execution.cs#L544) use a TestBlockingActivity that doesn't serialize correctly in the JSON serializer:
```csharp
                Body = new TestBlockingActivity("Block");
```

**Comment by zehavibarak** [comment]
Add to DurableInstancing InstanceValue:
```c#
    [KnownType(typeof(ActivityExecutor))]
    [KnownType(typeof(Variable<int>.VariableLocation))]
    [KnownType(typeof(Variable<string>.VariableLocation))]
```
in ActivityInstance, add IsReference = true
```c#
    [DataContract(Name = XD.ActivityInstance.Name, Namespace = XD.Runtime.Namespace, IsReference = true)]
```
