### ISSUE TITLE
AddNullKeyInFlowSwitch test broken

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#30]
Test is [here](https://github.com/dmetzgar/corewf/blob/678af1626bd825cfff5f0d6d0d72196fe62853df/test/TestCases.Activities/Flowchart/Switch.cs#L289)

**Comment by bcisnero** [comment]
I'll review this and hopefully, I'll have a solution very shortly

**Comment by bcisnero** [comment]
@dmetzgar so what exactly do you mean by "broken" Doesn't run? Don't output anything? Or, what's supposed to be the expected result from this test?

**Comment by dmetzgar** [comment]
Let me take a look at the test again.
