### ISSUE TITLE
Automatic CacheMetadata

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#4]
This should either be replaced with a reflection-based implementation or use the System.ComponentModel pieces from the .NET Standard 2.0.

**Comment by ewinnington** [comment]
Is there a battery of tests that check the functionality of CacheMetadata? 

I un-commented the Automatic CacheMetadata in my [branch](https://github.com/ewinnington/corewf) after moving to net standard 2.0 and was able to run the simplest test of removing the implementation of CacheMetadata in the Samples/Sequential. That test passed successfully.

**Comment by dmetzgar** [comment]
I think so. I'll add an issue to port some of the other tests we didn't port earlier.

**Comment by dmetzgar** [comment]
Added #19
