### ISSUE TITLE
Unable to find package CoreWf.Transactions

### ISSUE THREAD

**Issue by maskx** [UiPath/CoreWF#41]
when Install-Package CoreWf -Version 1.2.0, got an error message: 'Unable to find package CoreWf.Transactions. No packages exist with this id in source(s): '

**Comment by dmetzgar** [comment]
I'll have to check it out. The transactions DLL is included in the package instead of being used as an external package.

**Comment by OIgnt** [comment]
Agree with topic-starter. Version 1.2 cannot be installed via nuget because of missing dependency CoreWf.Transactions. Looking at CoreWf.Transactions we see that this dependency is listed there, but the link navigates us to 404 page.

**Comment by dmetzgar** [comment]
Version 1.2.1 is now published to NuGet with this fix. If `dotnet add` isn't picking this up, try clearing your NuGet HTTP cache:
```
dotnet nuget locals http-cache --clear
```
