### ISSUE TITLE
Add test failing due to different datetime formats

### ISSUE THREAD

**Issue by OIgnt** [UiPath/CoreWF#42]
Add test failing due to different date formats:

![image](https://user-images.githubusercontent.com/16219775/47961404-f046b900-e012-11e8-9327-59f75be09c68.png)

![image](https://user-images.githubusercontent.com/16219775/47961401-e0c77000-e012-11e8-8d39-98b8b854580d.png)

**Comment by dmetzgar** [comment]
Thanks @OIgnat! Could you submit a PR that uses invariant culture time?

**Comment by OIgnt** [comment]
@dmetzgar sure, just did it.

**Comment by dmetzgar** [comment]
Fixed by #44
