### ISSUE TITLE
Microsoft.CodeAnalysis.VisualBasic.Scripting cannot be restored

### ISSUE THREAD

**Issue by ThomasZitzler** [UiPath/CoreWF#49]
I tried to compile CoreWf, but nuget cannot restore the "Microsoft.CodeAnalysis.VisualBasic.Scripting" package. 

Where should that come from?

**Comment by ewinnington** [comment]
It requires the Roslyn feed from MyGet (See https://github.com/dotnet/roslyn ) 
https://dotnet.myget.org/F/roslyn/api/v3/index.json

Sorry about that, it's the new VB / C# compilation that requires it for the Dynamic XAML.

**Comment by ThomasZitzler** [comment]
Thanks, I added a nuget.config with that package source. now it's compiling, but I get the following warnings:
```
CoreWf.csproj : warning NU1603: CoreWf depends on Microsoft.CodeAnalysis.VisualBasic.Scripting (>= 2.8.0-dev-62823-01) but Microsoft.CodeAnalysis.VisualBasic.Scripting 2.8.0-dev-62823-01 was not found. An approximate best match of Microsoft.CodeAnalysis.VisualBasic.Scripting 2.8.1-beta6-62904-04 was resolved.
CoreWf.csproj : warning NU1701: Package 'Microsoft.CodeAnalysis.VisualBasic.Scripting 2.8.1-beta6-62904-04' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

```

So does it mean it now falls back to the full framework?

**Comment by ewinnington** [comment]
I’ve been using it on core, haven’t found something that throws a not supported or anything yet.

**Comment by ThomasZitzler** [comment]
See here: https://github.com/dotnet/roslyn/issues/13523

It seems there will be no official version...

**Comment by ThomasZitzler** [comment]
@ewinnington Did you try to compile/run it on linux? The whole porting of WF only makes sense when it's not platform/.net framework dependent. 

My main reason for using corewf would be to run our program in a linux docker container.

**Comment by ewinnington** [comment]
No, I was testing on windows using core. It should work everywhere. We might have to create that nuget for .net standard ourselves and check if there is any incompatibility. 

There is a Workflow runner working on core on https://github.com/ewinnington/wfRunnerCore that I’m using to test workflows. I’ll clone it to a Linux this weekend when I have a minute to myself.

Also thanks for the pull request. I’ll test it and merge it this weekend.

**Comment by ThomasZitzler** [comment]
@lbargaoanu Would you please reopen that issue? I think it is quite problematic that there is no official version of the VB scripting package and the current verison is already behind in version numbers.

For example I cannot reference my test project in an asp.net core web application as there are already dependencies to Microsoft.CodeAnalysis.Common from other places (System.Activities 1.2.2 is my local copy of the CoreWF package, seems the package name is also generated as System.Activities after the rename)

```
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. 
Install/reference Microsoft.CodeAnalysis.Common 2.8.0 directly to project Tix.Demo.Activities to resolve this issue. 
 Tix.Demo.Activities -> Tix.Workflows -> Tix.Console -> Tix.DomainServices -> Microsoft.AspNetCore.Mvc 2.2.0 -> Microsoft.AspNetCore.Mvc.TagHelpers 2.2.0 -> Microsoft.AspNetCore.Mvc.Razor 2.2.0 -> Microsoft.CodeAnalysis.Razor 2.2.0 -> Microsoft.CodeAnalysis.Common (>= 2.8.0) 
 Tix.Demo.Activities -> Tix.Workflows -> System.Activities 1.2.2 -> Microsoft.CodeAnalysis.VisualBasic.Scripting 2.8.0-dev-62823-01 -> Microsoft.CodeAnalysis.Scripting.Common 2.8.0-dev-62823-01 -> Microsoft.CodeAnalysis.Common (= 2.8.0-dev-62823-01).	
```

**Comment by lbargaoanu** [comment]
Yes, it is. And a PR is welcome. But at the moment this isn't much of an issue for us, so I don't plan to do anything about it in the near future.
