### ISSUE TITLE
Use OmniXAML

### ISSUE THREAD

**Issue by birbilis** [UiPath/CoreWF#5]
Have you considered using OmniXAML?

Have read that in the past it didn't support x:Class that was needed for WF, but now it does (in v2):
https://github.com/SuperJMN/OmniXAML/issues/12

**Comment by dmetzgar** [comment]
Thanks for the suggestion! It's definitely worth looking into. There are some classes we need that are set to come out with .NET Standard 2.0. I suspect I'll have to wait until then, but it's worth trying OmniXAML in the meantime.

**Comment by dmetzgar** [comment]
Instead of OmniXAML, I think Portable.Xaml looks more promising. I'll close this issue and open one for Portable.Xaml.
