### ISSUE TITLE
Renamed to System.Activities

### ISSUE THREAD

**Issue by lbargaoanu** [UiPath/CoreWF#51]
For backward compatibility. Everything still works as far as I can tell.

**Comment by dmetzgar** [comment]
What did you do with the CoreWf.Transactions code? System.Transactions is part of .NET Core 2.0 but not part of .NET Standard. I copied the code to CoreWf.Transactions to get unblocked but I'm curious if you rename it back to System.Transactions then using System.Activities in a .NET Core project may have a conflict.

**Comment by lbargaoanu** [comment]
I didn't give it much thought :) But it's called System.Activities.Transactions, so there shouldn't be any conflicts. It [does](https://docs.microsoft.com/en-us/dotnet/api/?view=netstandard-2.0&term=System.Transactions) seem to be a part of .Net Standard 2.0 now, so maybe we can do better here.

**Comment by lbargaoanu** [comment]
@dmetzgar Check #53.
