### ISSUE TITLE
Replace Portable.Xaml with System.Xaml

### ISSUE THREAD

**Issue by lbargaoanu** [UiPath/CoreWF#54]
We need https://github.com/dotnet/wpf/issues/46.

**Comment by ewinnington** [comment]
I was wondering if it is best to pull it in as a submodule while developing, then see if we can get split it into a separate assembly for easy nuget-ing.

**Comment by lbargaoanu** [comment]
I'm hoping they'll do that eventually :) Meanwhile I think we can live with Portable.Xaml. I've opened the issue to let people know what the next big step is.

**Comment by bcisnero** [comment]
Hi guys, sorry if my question sounds dumb but I'm new in all this open source movement and I want to start contributing but I'm not really sure where or with what to begin. I've checked the issues list but it really doesn't tell me if I can start doing something or is only a discussion planning or something like this one where is an enhancement and is open but apparently is not ready to start doing anything with it. So is there something that I can start doing that you guys know of?

**Comment by lbargaoanu** [comment]
It's difficult to say without investigating deeper which of the open issues would be best to start with. You could start with the tests that don't quite work. I'm not sure if there is an issue for every problem there. But some tests are flaky, some are already skipped.

**Comment by bcisnero** [comment]
Ok, thanks for your response. I'll do that.
