### ISSUE TITLE
WorkflowApplication.ResumeBookmark starts workflow from beginning

### ISSUE THREAD

**Issue by zehavibarak** [UiPath/CoreWF#56]
WorkflowApplication.ResumeBookmark starts workflow from beginning, prior to attempting resumption

**Comment by lbargaoanu** [comment]
There is no need for a new issue. Please continue the discussion in the issue you've already open.

**Comment by zehavibarak** [comment]
This is a more accurate description

**Comment by lbargaoanu** [comment]
I've renamed the old issue.
