### ISSUE TITLE
Porting Workflow Designer to .NET Core 3

### ISSUE THREAD

**Issue by nguyencongle** [UiPath/CoreWF#58]
As .NET Core 3 supports WPF, so I want to make experiments to port the Workflow Designer.
Where can I find the source code and unit tests of these dlls:
System.Activities.Presentation
System.Activities.Core.Presentation
Thank you.

**Comment by ewinnington** [comment]
Great question, we didn’t previously have access to any WPF code. Now maybe you can find the code at: 

- https://github.com/dotnet/wpf/

- https://github.com/microsoft/referencesource

- Here for reference only: https://referencesource.microsoft.com/#System.Activities.Core.Presentation/System/Activities/Presentation/ActivityDesignerHelper.cs,1fcd5d280987e85b

I would love to find out where more tests for WF are. I know there must be more but they were not open sourced at the time. We would need someone at MS to go look for them.

**Comment by nguyencongle** [comment]
Yes, I can see the source code at 
https://github.com/microsoft/referencesource
but I can't find the unit tests for it.
So if I can make it run in .NET Core 3, it's still hard to tell if everything is ok because the source code of these components is huge.

**Comment by lbargaoanu** [comment]
I'll close this as it's out of scope for this repo.

**Comment by ewinnington** [comment]
I disagree that it’s out of scope. It’s an important component for the support of WF in the future. Perhaps it does not interest UiPath, but for other users of WF it is useful.

**Comment by lbargaoanu** [comment]
What's that got to do with this repo? There is no such code here. Why would you discuss this here?

**Comment by ewinnington** [comment]
The workflow designer components are explicitly part of Workflow Foundation, now that .NET 5 will support WPF, we should investigate if we can bring forward the parts of the code to support the designer in the future. If we can't discuss the designer component of WF here, then were?

Maybe we will be able to put them into a different assembly or nuget package for those who don't need it. 

I wouldn't want to discourage someone who is prepared to help us move coreWF forward, especially since we don't yet have a designer running under core / windows.

**Comment by ewinnington** [comment]
> So if I can make it run in .NET Core 3, it's still hard to tell if everything is ok because the source code of these components is huge.

@nguyencongle 
Please try. Once you have something running, I'm sure we can find someone who has access to the tests - or write our own.

**Comment by nguyencongle** [comment]
It's quite straightforward to port Workflow Designer, because all the core WPF dlls were there in .NET Core. But looks like this is not the right place to discuss around.

**Comment by lbargaoanu** [comment]
You should host that code in a new repo and start porting it.

**Comment by yekanchi** [comment]
It might be right that this issue may have nothing with this repo, but eventually it could be integrated to the current project. if @nguyencongle or someone else can provide a minimal working designer under .Net Core platform it's a huge leap forward.

**Comment by Marius-TV** [comment]
Even though .NET Core 3 supports WPF, it is Windows only. The purpose of this repo is to modernize WF Engine and make it cross-platform. If someone else starts a new repo for the WPF Designer we would gladly help with the integration. Long-term we would like to invest more in a web WF Designer.

**Comment by vologar** [comment]
So no designer in CoreWF and none is coming? This is one of the major and integral features in WF: Ability to visually present and modify complex workflows.  What's the point of having just an "engine" ?
