### ISSUE TITLE
Load and edit workflows in .NET Framework Designer

### ISSUE THREAD

**Issue by marcowalz** [UiPath/CoreWF#59]
Hallo

in our company we use .NET Framework Rehosted Workflow Designer to create and edit workflows.
Actually we use it only on windows machines. But we want to switch to .NET Standard to also able to use Linux machines.

Creating and executing activities with CoreWF works perfect acutally. But we need the ability to create and edit workflows with .NET rehosted workflow designer.

When I try to load a workflow file into the designer I will get a message that the contextproperty is not set.
The workflow file was created by CoreWF (and Portable.Xaml).

Is there a change to get it work ?

Thanks in advance!

**Comment by ewinnington** [comment]
Do you have a repo with a simple example we can use to repro and investigate?

**Comment by marcowalz** [comment]
I create a smale repo. How can I send it?

Here is the WPF-App:

`
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            try
            {
                this.Test();
            }
            catch (Exception ex)
            { }
        }

        private void Test()
        {
            var activity = new TestActivity();

            WorkflowDesigner designer = new WorkflowDesigner();

            (new DesignerMetadata()).Register();

            DesignerBorder.Child = designer.View;
            designer.Load(activity);
        }
    }
`
The TestActivity-Class:

`    
class TestActivity : CodeActivity
    {
        public InArgument<string> Text { get; set; }

        protected override void Execute(CodeActivityContext context)
        {
            throw new NotImplementedException();
        }
    }
`

If I use the .NET Framework System.Activities.dll it works fine - the designer shows the activity. If I switch to the CoreWF.dll (Namespace: System.Activities) the designer shows an empty space.

.NET Framework:
![image](https://user-images.githubusercontent.com/52446845/62972620-bcf05080-be14-11e9-86c8-6262fe7e6375.png)
