### ISSUE TITLE
FileInstanceStore Error...

### ISSUE THREAD

**Issue by cheesiong79** [UiPath/CoreWF#61]
I try to run FileInstanceStore Samples Project (**BookmarkConsoleApp)** and I encounter an error in the **LoadWorkflow** function.

{"Could not convert string 'e0f9ec98-30a2-4641-b760-5abcbb2fa5bb' to dictionary key type 'CoreWf.Bookmark'. Create a TypeConverter to convert from the string to the key type object. Path 'Value.bookmarkMgr.bookmarks.e0f9ec98-30a2-4641-b760-5abcbb2fa5bb', line 12, position 47."} | Newtonsoft.Json.JsonSerializationException

**Comment by lbargaoanu** [comment]
That's just a sample. We should probably delete it.
