### ISSUE TITLE
Support xml serialization

### ISSUE THREAD

**Issue by zehavibarak** [UiPath/CoreWF#68]
Microsoft is backing out of Newtonsoft JSON package in favor of it's own implementation. If we were to serialize the InstanceStore without depending on Newtonsoft to deep serialize object type to be able to later deseralize it, two changes to code should be made:
- ActivityInstance
```c#
[DataContact(IsReference = true)]
```
- InstanceValue 
```c#
[KnownType(typeof(ActivityExecutor))]
    [KnownType(typeof(Variable<int>.VariableLocation))]
    [KnownType(typeof(Variable<string>.VariableLocation))]
```
Having done these we can use `DataContractSerializer.WriteObject()`, resulting in an xml we may persist.

**Comment by lbargaoanu** [comment]
https://github.com/UiPath/corewf/issues/15#issuecomment-542737267
