### ISSUE TITLE
Persist a completed wf after resuming fails

### ISSUE THREAD

**Issue by zehavibarak** [UiPath/CoreWF#69]
Due to changes made during last couple of months. Prior to that, it used to work. The PersistableIdle fails if returns PersistableIdleAction.Persist when reaching end of flow.

**Comment by lbargaoanu** [comment]
A PR is welcome. With a fix or at least a failing test. The existing tests pass.

**Comment by LunicLynx** [comment]
@zehavibarak Can you give a bit more detail?
I think i ran into the same issue.

A stack trace / exception etc. would be really helpful.

**Comment by zehavibarak** [comment]
@LunicLynx think the issue was you have to manually call workflowApplication Unload() in order to the store to persist - or call Persist() returning PersistableIdleAction.None on PersistableIdle.
