### ISSUE TITLE
Implement xaml code generation

### ISSUE THREAD

**Issue by danielmeza** [UiPath/CoreWF#70]
This issue is for track the c# code behind generation based on the XAML activity representation.

**Comment by lbargaoanu** [comment]
What does that mean?

**Comment by danielmeza** [comment]
@lbargaoanu better?

**Comment by lbargaoanu** [comment]
That sounds like a XAML designer concern, it's out of scope for this repo. This is about the workflow engine itself.

**Comment by danielmeza** [comment]
@lbargaoanu there is some place for track the designer? in order to put this issue.

**Comment by lbargaoanu** [comment]
To be honest I don't know if someone started that work or not.

**Comment by danielmeza** [comment]
Maybe related to https://github.com/UiPath/corewf/issues/70?

**Comment by danielmeza** [comment]
Maybe related to https://github.com/UiPath/corewf/issues/59 ?
