### ISSUE TITLE
Port from existing wf activities guide

### ISSUE THREAD

**Issue by danielmeza** [UiPath/CoreWF#74]
Hi guys first let me say thanks you for this excellent work.

There is a guide o doc to port activities from a existing project?

**Comment by lbargaoanu** [comment]
There is no need for that. The API is exactly the same. You just need to retarget for .Net Core 3.0 or .Net Standard. There is MS documentation about that.

**Comment by danielmeza** [comment]
This mean that it will support existing .xaml activities? And if not which are the limitations. We need also a roadmap and a wiki or related link to engage people in the right path

**Comment by lbargaoanu** [comment]
Yes. About the wiki, what it should contain? Try starting one, open a PR.

**Comment by danielmeza** [comment]
Ok, I will try to make a Wiki menu to start and ask you for help to fill some knowledge  gaps I have.

**Comment by ewinnington** [comment]
There's a example of a command line workflow runner to test your [execution of workflows](https://github.com/ewinnington/wfRunnerCore) on my repo, you can have a look at the ActivityLibraryCore folder for examples of C# activities and at the wfRunnerCore/Workflows folder for some XAML workflows. Might help to get started.

If you have followed any WorkflowFoundation tutorial you should be able to understand and use the code. Please ask if you need help. I'd be happy to contribute to the Wiki, if you tell me what I need to write about to help you.

**Comment by danielmeza** [comment]
@ewinnington thanks you! I'm now busy, but we have schedule a project migration from WF on .NET Framework to Core WF thanks to the work you do, when I start to migrate I will take time to take note over how the wiki will be and a migration steps to help people embrace this repo. Thanks you again
