### ISSUE TITLE
Is there a way to compile XAML workflows using CoreWF?

### ISSUE THREAD

**Issue by ghost** [UiPath/CoreWF#82]
Hi there!

I know that XAML workflows can be loaded with ActivityXamlServices. But is there anyway to compile XAML workflows using CoreWF? If not, do you know of any resource I could use to learn how to create this functionality?

Thank you for your help,
Stephen

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by weatherheadio** [comment]
No problem. For anyone else looking, I've asked this at https://stackoverflow.com/questions/60361360/is-there-a-way-to-compile-xaml-workflows-using-corewf

Thanks,
Stephen
