### ISSUE TITLE
Any way of getting the migration of System.Activities.DynamicUpdate

### ISSUE THREAD

**Issue by casbelt** [UiPath/CoreWF#99]
Hello,

I am in the middIe of a migration to net core and I am trying to get a class from DynamicUpdate spacename (NativeActivityUpdateMapMetadata)
I have installed the nuget package Core.Wf in my project but when I try to access to DynamicUpdate namespace it does not appears to be chosen.

![image](https://user-images.githubusercontent.com/8917003/77736268-51a66800-700c-11ea-8a5c-3bf107ee2e6f.png)

Am I doing something wrong?

Thanks in advance!

**Comment by lbargaoanu** [comment]
Why do you need that?

**Comment by casbelt** [comment]
Hi,
I am trying to override a method from the class NativeActivity, "OnCreateDynamicUpdateMap"


![image](https://user-images.githubusercontent.com/8917003/77755737-2896cf00-702e-11ea-8486-9eb10f8aa37e.png)


The method receive as first argument a NativeActivityUpdateMapMetadata class which belongs to DynamicUpdate namespace. I don´t know how to replicate this class in net core.

Thanks again

**Comment by lbargaoanu** [comment]
So you're really using dynamic update. That's an advanced feature we're not ready to port at this time. We're trying to reduce the scope of this project.

**Comment by dmetzgar** [comment]
@casbelt dynamic update is only used for upgrading persisted instances from an older workflow version to a newer one. The feature is fairly complex and quite rarely used so it's been left out of CoreWF. Although if you really need it, we'd appreciate a PR.

**Comment by lbargaoanu** [comment]
@dmetzgar Even that seems tricky. The way that was implemented it was tightly coupled to the base class `Activity`. I wouldn't want that now. I would expect the implementation to live in the higher level package, UiPath.Workflow, not in the core package. So it wouldn't be a straightforward port.

**Comment by lbargaoanu** [comment]
Just to be clear, I did previously port dynamic update and then removed it again yesterday in #100.

**Comment by casbelt** [comment]
Hello,
it´s a pity.

Thanks for your time and dedication.
